### ISSUE TITLE
localAuthenticationProvider

### ISSUE THREAD

**Issue by argestes** [jthoms/spring-security-mongodb#1]
Hello, and thanks for this great project!. I'm kind of new to Spring Framework and I don't understand how Spring knows that localAuthenticationProvider is LocalAuthenticationProvider class?
I really appreciate any help.
Thanks

**Comment by jthoms** [comment]
Hi yigitunlu,
The framework loads and resolves all beans annotated with @Component (or @Service, etc., excluding @Controller) via this block in src/main/resources/META-INF/spring/ApplicationContext.xml:
`<context:component-scan base-package="com.sustia">
    <context:exclude-filter expression="org.springframework.stereotype.Controller" type="annotation" /></context:component-scan>`

You could register localAuthenticationProvider explicitly instead via
`<bean id="localAuthenticationProvider" class="com.sustia.service.LocalAuthenticationProvider"/>`

Also, if you prefer Java classes to XML configuration, see:
http://static.springsource.org/spring/docs/3.2.x/spring-framework-reference/htmlsingle/#beans-java

Thanks,
John
